# values.yaml - default values for the Helm chart

replicaCount: 1  # open /opt/ts/config.db: permission denied

image:
  name: "ghcr.io/yourok/torrserver:MatriX.136"
  pullPolicy: IfNotPresent

service:
  nodePort: "30890"
  port: "8090"
  targetPort: &serviceTargetPort "8090"
  type: LoadBalancer

volumes:
  hostPath: ""
  targetMountPath: &volumesTargetMountPath "/opt/ts"

containers:
  main:
    command: ["/usr/bin/torrserver"]
    args:
    - --httpauth
    - --port
    - *serviceTargetPort
    - --ip=0.0.0.0
    - --path
    - *volumesTargetMountPath

# Node scheduling constraints:
nodeSelector: {}
# Optional nodeSelector map to restrict scheduling (empty by default).

tolerations: []
# Optional list of tolerations (empty means we do not tolerate master taints,
# so pods will not run on tainted masters by default:contentReference[oaicite:2]{index=2}).

affinity: {}
# Optional affinity rules. We will define required anti-affinity in the
# template to avoid master nodes.
